# Erasmus Neural Networks
http://michalbereta.pl/nn
## Perceptron learning


## Before you start

Exacute the examples.

Then, do the tasks and send back the notebook.

Change the name of this notebook according to the schema: {YourSurname}\_{YourFirstName}\_{OriginalFileName}.

Be sure to fill all places with "YOUR ANSWER HERE".

When ready, send the notebook, with all the necessary files zipped, to the teacher.

### Simple perceptron example

Start with initial weights, check the answer for some input values. If there is a misclassification, update the weights.

Observe that, even after one update, the perceptron is closer to the correct answer.

Experiment with different starting values.

In [1]:
#!/usr/bin/env python
import numpy as np

#initial weights
w = np.array([0.3, -0.4])
w0 = 0.1 #bias weight

print('initial weights, w=',w,' w0=',w0)

#input vector
x = np.array([-0.5, 0.9 ])
#class label, 1 or -1
d = 1 

print('example x=',x,' is from class ',d)

#learning rate
eta = 0.1


y = np.dot(w,x) + w0
print('weighted sum, y=',y)

#activation function
if y > 0:
    u = 1
else:
    u = -1
    
print('percetron says: x is from class ',u)
    
if u!=d:
    w[0] = w[0] + eta*x[0]*d
    w[1] = w[1] + eta*x[1]*d
    w0 = w0 + eta*1*d


print('weights after update, w=',w,' w0=',w0)

y = np.dot(w,x) + w0
print('weighted sum, y=',y)

#activation function
if y > 0:
    u = 1
else:
    u = -1    
print('percetron says: x is from class ',u)


initial weights, w= [ 0.3 -0.4]  w0= 0.1
example x= [-0.5  0.9]  is from class  1
weighted sum, y= -0.41000000000000003
percetron says: x is from class  -1
weights after update, w= [ 0.25 -0.31]  w0= 0.2
weighted sum, y= -0.20400000000000001
percetron says: x is from class  -1


### Simple perceptron example 2

Start with initial weights, check the answer for some input values. 

If there is a misclassification, update the weights until the answer is correct.

Experiment with different starting values.

In [2]:
#!/usr/bin/env python
import numpy as np

#initial weights
w = np.array([0.3, -0.4])
w0 = 0.1 #bias weight

#input vector
x = np.array([-0.5, 0.9 ])
#class label
d = 1 

print('example x=',x,' is from class ',d)

#learning rate
eta = 0.1


y = np.dot(w,x) + w0
print('weighted sum, y=',y)

#activation function
if y > 0:
    u = 1
else:
    u = -1
    
print('percetron says: x is from class ',u)
    
while u!=d:
    w[0] = w[0] + eta*x[0]*d
    w[1] = w[1] + eta*x[1]*d
    w0 = w0 + eta*1*d
    print('\nweights after update, w=',w,' w0=',w0)
    y = np.dot(w,x) + w0
    print('weighted sum, y=',y)
    #activation function
    if y > 0:
        u = 1
    else:
        u = -1    
    print('percetron says: x is from class ',u)

print('learning done')

example x= [-0.5  0.9]  is from class  1
weighted sum, y= -0.41000000000000003
percetron says: x is from class  -1

weights after update, w= [ 0.25 -0.31]  w0= 0.2
weighted sum, y= -0.20400000000000001
percetron says: x is from class  -1

weights after update, w= [ 0.2  -0.22]  w0= 0.30000000000000004
weighted sum, y= 0.0020000000000000573
percetron says: x is from class  1
learning done


### 2D data from normal distributions

In [ ]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

#example data from two classes; 2D normal distributions
num = 100
x2 = np.random.multivariate_normal([-2,-2], np.array([[1,0],[0,1]]),num)
x1 = np.random.multivariate_normal([2,2], np.array([[1,0],[0,1]]),num)
xmin = -6
xmax = 6
ymin = -6
ymax = 6

plt.xlim(xmin,xmax)
plt.ylim(ymin,ymax)

plt.plot(x1[:,0],x1[:,1],'o')
plt.plot(x2[:,0],x2[:,1],'o')

plt.show()

### Perceptron online learning animation

#### DO NOT USE THIS CODE AS A TEMPLATE FOR YOUR PROGRAMS!

In [ ]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import animation
from time import time


num = 100
x0 = np.random.multivariate_normal([2,2], np.array([[1,0],[0,1]]),num)
x0 = np.hstack((np.repeat(1,num).reshape(num,1), x0)) #adding bias signal explicitly
d0 = np.repeat(0, num)
x1 = np.random.multivariate_normal([-2,-2], np.array([[1,0],[0,1]]),num)
x1 = np.hstack((np.repeat(1,num).reshape(num,1), x1)) #adding bias signal explicitly
d1 = np.repeat(1, num)

X = np.vstack((x0,x1))
d = np.hstack((d0,d1))


def perceptron(x, w):
    u = np.dot(x, w)
    y = 1 if u>0 else 0
    return y

epoch = 100
eta = 0.01

iteration = epoch*X.shape[0]

weights = np.random.random(3) #perceptoron weights
a = -weights[1]/weights[2]
b = -weights[0]/weights[2]

xx = np.linspace(-6 ,6 ,100)
yy = a*xx+b



fig = plt.figure()
ax = fig.add_subplot(111)
ax.set_xlim(-6, 6)
ax.set_ylim(-6, 6)
ax.scatter(x0[:,1], x0[:,2], color='r')
ax.scatter(x1[:,1], x1[:,2], color='g')
ax.plot(xx,yy, lw=2, c='k')

def animate(i):
    flag=False
    e, p = divmod(i,X.shape[0])
    global weights
    y = perceptron(X[p,:], weights)
    if y==1 and d[p]==0:
        flag = True
        weights -= eta*X[p,:]
    if y==0 and d[p]==1:
        flag=True
        weights += eta*X[p,:]
    if flag:
        a = -weights[1]/weights[2]
        b = -weights[0]/weights[2]
        yy = a*xx+b
        ax.clear()
        ax.scatter(x0[:,1], x0[:,2], color='r')
        ax.scatter(x1[:,1], x1[:,2], color='g')
        ax.scatter(X[p,1], X[p,2], color='k', s=80)
        ax.plot(xx,yy, lw=2, c='k')
        ax.text(0.0, -5.0, 'epoch: {0}, sample: {1}'.format(e,p))
        ax.set_xlim(-6, 6)
        ax.set_ylim(-6, 6)
    return ax,

dt = 1./30
t0 = time()
animate(0)
t1 = time()
interval = 100 * dt - (t1 - t0)

anim = animation.FuncAnimation(fig, animate, frames=iteration, interval=interval)

plt.show()

### Perceptron batch learning animation

#### DO NOT USE THIS CODE AS A TEMPLATE FOR YOUR PROGRAMS!

In [ ]:
%matplotlib notebook
import numpy as np
import matplotlib.cm as cm
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
import matplotlib.animation as animation

#example data from two classes, 2D normal distribution
num = 100
x2 = np.random.multivariate_normal([-2,-2], np.array([[1,0],[0,1]]),num)
x1 = np.random.multivariate_normal([2,2], np.array([[1,0],[0,1]]),num)
xmin = -6
xmax = 6
ymin = -6
ymax = 6

#initialization of weights - random, smal values, positive and negative values
#w[0] is the bias weight
w = 2*np.random.rand(3) - 1
#w = np.zeros(3) #try it: in general, initialization of weigths to zero is not a good idea
print(w)


delta = 0.01 #accuracy of the grid for vizualization only
x = np.arange(xmin, xmax, delta)
y = np.arange(ymin, ymax, delta)
X, Y = np.meshgrid(x, y)
Z = X*w[1] + Y*w[2] + w[0]

fig = plt.figure()

plt.xlim(xmin,xmax)
plt.ylim(ymin,ymax)
plt.plot(x1[:,0],x1[:,1],'o')
plt.plot(x2[:,0],x2[:,1],'o')

#this function is one iteration of perceptron learning
def update(i):
    global w
    print()
    print('iteration=',i)

    #perceptron responses to examplse from class 1, 
    #we assume they should be  > 0
    ans1 = np.dot(x1, w[1:]) + w[0]  
    errors1 = (ans1<=0).sum() # number of missclassifications from class 1
    print('errors1=',errors1)
    M1 = x1[ans1<=0] #selected examples that are missclassified from class 1
    criterion1 = ans1[ans1<=0].sum() #perceptron criterion - part 1 from the class 1
    print('criterion1=',criterion1)

    #perceptron responses to examplse from class 2, 
    #we assume they should be  <= 0    
    ans2 = np.dot(x2, w[1:]) + w[0]
    errors2 = (ans2>0).sum() # number of missclassifications from class 2
    print('errors2=',errors2)
    M2 = x2[ans2>0] #selected examples that are missclassified from class 2
    criterion2 = ans2[ans2>0].sum()#perceptron criterion - part 2 from the class 1
    print('criterion2=',criterion2)
    
    #full perceptron criterion -we should minimize it 
    criterion = np.abs(criterion1) + np.abs(criterion2) 
    print('criterion=',criterion)

    M1 = M1.sum(axis=0) #summed errors from class 1
    M2 = M2.sum(axis=0) #summed errors from class 2
    M = M1 - M2 #vector giving the direction of the change of the weights vector
    
    print('M=',M)
    eta = 0.005 #learning rate
    
    #weights modification
    if np.abs( M.sum() ) > 0: #or: if criterion > 0:
        w[1] += eta*M[0]
        w[2] += eta*M[1]
        w[0] += eta*(errors1-errors2) #bias weight modification 
        #a trick : normalization of the weight vector
        #connected with the learning rate - both influence the convergence of the training process        
        w = w/np.linalg.norm(w) 
    else:
        print('learning done')
    print('w=',w)
    
    #vizualization
    plt.clf()
    plt.plot(x1[:,0],x1[:,1],'o')
    plt.plot(x2[:,0],x2[:,1],'o')
    Z = X*w[1] + Y*w[2] + w[0]
    Z[Z>0] = 1
    Z[Z<=0] = -1
    im = plt.imshow(Z, interpolation='bilinear', cmap=cm.hot,
                origin='lower', extent=[xmin, xmax, ymin, ymax],
                vmax=abs(Z).max(), vmin=-abs(Z).max())

    
#start learning
ani = animation.FuncAnimation(fig, update, interval=1000, blit=False)
plt.show()

print('end')

### Line separating two points (no bias version)

Does it work for any two points?

Check for example:

```
x1 = np.array([-2, -2]) #from class 1
x2 = np.array([-4, -4]) # from class -1
```

In [ ]:
#!/usr/bin/env python
import numpy as np
import matplotlib.cm as cm
import matplotlib.mlab as mlab
import matplotlib.pyplot as plt
import matplotlib.animation as animation


xmin = -6
xmax = 6
ymin = -6
ymax = 6

x1 = np.array([4, 4]) #from class 1
x2 = np.array([-4, -4]) # from class -1


w = (x1 - x2)/2.0
print(w)


delta = 0.01 #accuracy of the grid for vizualization only
x = np.arange(xmin, xmax, delta)
y = np.arange(ymin, ymax, delta)
X, Y = np.meshgrid(x, y)

fig = plt.figure()
plt.xlim(xmin,xmax)
plt.ylim(ymin,ymax)
plt.plot(x1[0],x1[1],'o')
plt.plot(x2[0],x2[1],'o')
plt.plot(0,0,'o') #origin
    
#vizualization
Z = X*w[0] + Y*w[1]
Z[Z>0] = 1
Z[Z<=0] = -1
im = plt.imshow(Z, interpolation='bilinear', cmap=cm.hot,
            origin='lower', extent=[xmin, xmax, ymin, ymax],
            vmax=abs(Z).max(), vmin=-abs(Z).max())

plt.show()
print('end')

### Line separating two points (version with bias)

Does it work for any two points?

Check for example:

```
x1 = np.array([-2, -2]) #from class 1
x2 = np.array([-4, -4]) # from class -1
```

In [3]:
#!/usr/bin/env python
import numpy as np
import matplotlib.cm as cm
import matplotlib.pyplot as plt


xmin = -6
xmax = 6
ymin = -6
ymax = 6

x1 = np.array([-2, -1]) #from class 1
x2 = np.array([-4, -4]) # from class -1

v = x1 - x2
mid = (x1 + x2)/2.0

w = v
w0 = -v[0]*mid[0] - v[1]*mid[1]

print(w, w0)

print('for x1: ', np.dot(w,x1) + w0)
print('for x2: ', np.dot(w,x2) + w0)

delta = 0.01 #accuracy of the grid for vizualization only
x = np.arange(xmin, xmax, delta)
y = np.arange(ymin, ymax, delta)
X, Y = np.meshgrid(x, y)

fig = plt.figure()
plt.xlim(xmin,xmax)
plt.ylim(ymin,ymax)
plt.plot(x1[0],x1[1],'o')
plt.plot(x2[0],x2[1],'o')
plt.plot(0,0,'o') #origin
    
#vizualization
Z = X*w[0] + Y*w[1] + w0
Z[Z>0] = 1
Z[Z<=0] = -1
im = plt.imshow(Z, interpolation='bilinear', cmap=cm.hot,
            origin='lower', extent=[xmin, xmax, ymin, ymax],
            vmax=abs(Z).max(), vmin=-abs(Z).max())
 

plt.show()

print ('end')

[2 3] 13.5
for x1:  6.5
for x2:  -6.5


<Figure size 640x480 with 1 Axes>

end


### Task 1
What happens when the data generated and used for perceptron training is not linearly separable? Can the perceptron algorithm still be used? How is the value of training rate (eta) important in such a case?



If the data is not linearly separable, the perceptron might not converge. A too high learning rate will induce big adjustements of weights at each iteration, which in case of non linearly separable data will oscillate between extreme values and never converge. A lower learning rate will slowly adjust the weights but may take too many epochs to converge to an optimal solution. That's why if we use the perceptron, it will be important to define a maximum number of epoch and maybe also a maximum number of errors allowed. Moreover, if we already know that the data is non linearly separable, it's better to use a non linear activation function (sigmoid, hyberbolic tangent, etc).

### Task 2

Prepare your own implementation of perceptron learning

– Use the online or batch mode

– Be ready for any number of attributes (inputs to perceptron)


In [4]:
import numpy as np

class Perceptron:
    def __init__(self, dim, learningrate=0.1, bias=1):
        self.weights=np.zeros(dim)
        self.learningrate = learningrate
        self.bias = bias
    
    def activation(self, x):
        return 1 if x > 0 else -1
    
    def predict(self, inputs):
        guess=[]
        for i, input in enumerate(inputs):
            sum=np.dot(self.weights,input) + self.bias #il faudrait incorporer le bias au weights w0
            # Activation function 
            guess.append(self.activation(sum))
        return guess
    
    def learn(self, inputs, labels):
        epoch=0
        errors=1
        while errors and epoch < 100 :
            errors=0
            print("Epoch "+str(epoch)+"\n")
            for i, input in enumerate(inputs):
                # Scalar product weights/inputs + bias
                sum=np.dot(self.weights,input) + self.bias 
                # Activation function 
                u=self.activation(sum)
                if u != labels[i]:
                    errors+=1
                    # Ajust weights and bias 
                    for j in range(len(self.weights)): 
                        self.weights[j] += self.learningrate*input[j]*labels[i]
                    self.bias += self.learningrate*labels[i]
            print(self.weights, "\nerrors = ", errors)
            epoch+=1
            
    def __str__(self):
        return '(' + str(self.weights)  + ')'
    def __repr__(self):
        return '(' + str(self.weights) + ')'

p1=Perceptron(4)
p1          
p1.learn([[8,7,9,6], [7,7,7,6], [6,7,6,6]], [1,-1,-1])




Epoch 0

[-0.7 -0.7 -0.7 -0.6] 
errors =  1
Epoch 1

[-0.6 -0.7 -0.5 -0.6] 
errors =  2
Epoch 2

[-0.5 -0.7 -0.3 -0.6] 
errors =  2
Epoch 3

[-0.4 -0.7 -0.1 -0.6] 
errors =  2
Epoch 4

[-0.3 -0.7  0.1 -0.6] 
errors =  2
Epoch 5

[-0.2 -0.7  0.3 -0.6] 
errors =  2
Epoch 6

[-0.1 -0.7  0.5 -0.6] 
errors =  2
Epoch 7

[-2.22044605e-16 -7.00000000e-01  7.00000000e-01 -6.00000000e-01] 
errors =  2
Epoch 8

[ 0.1 -0.7  0.9 -0.6] 
errors =  2
Epoch 9

[ 0.1 -0.7  0.9 -0.6] 
errors =  0


### Task 3

Use the 5D data to train your perceptron based on examples from data5D_train.csv. Last column is the class label.

Generate answers (as 1 or -1) for data in data5D_test.csv and save them to a file.

In [5]:
f = open('data5D_train.csv','r')
lines = f.readlines()
values=[]
labels=[]
for l in lines:
    item=l.split()
    item.pop()
    values.append(np.array(item, dtype="float"))
    labels.append(float(l.split().pop()))
print("values = ", values, len(values))
print("\n labels = ", labels)
f.close()

values =  [array([-0.45219426,  0.25657125, -0.9368542 ,  0.80657558, -0.79133903]), array([-0.72172939,  0.01179515,  0.40583078, -0.90642659,  0.07723489]), array([-0.04764479, -0.98419792,  0.5544936 , -0.8359505 ,  0.05949989]), array([ 0.71859074, -0.08114127,  0.4021709 ,  0.09331177, -0.88052225]), array([ 0.64350499,  0.32052622,  0.40639275, -0.71094315,  0.44726582]), array([-0.64359573, -0.73152814,  0.52228294,  0.30746542,  0.95632172]), array([0.50235318, 0.98221024, 0.61809971, 0.79572339, 0.33163849]), array([-0.36905117, -0.77977007, -0.86780395, -0.99407331, -0.99991774]), array([-0.95085337,  0.58128767,  0.88991417,  0.4544718 , -0.81981303]), array([-0.34266327, -0.25388755,  0.29505976, -0.11738547, -0.50671621]), array([ 0.23419711,  0.90957132,  0.36975825, -0.50976055, -0.84761044]), array([-0.98283687,  0.40109125,  0.56837772,  0.22437724,  0.34702004]), array([-0.29067109,  0.51960902,  0.82073838,  0.19444032,  0.22192982]), array([-0.65682617,  0.40510063,

In [6]:
p2=Perceptron(len(values[0]))          
p2.learn(values, labels)


Epoch 0

[ 0.07553725 -0.19610503  0.06159207 -0.64933547  0.46879926] 
errors =  36
Epoch 1

[ 0.04944294 -0.08274571  0.09759394 -0.78882254  0.58306662] 
errors =  15
Epoch 2

[ 0.08581935 -0.19627008  0.08388106 -0.84210278  0.69415417] 
errors =  16
Epoch 3

[ 0.06385658 -0.23748753  0.10822428 -0.92079196  0.65192312] 
errors =  7
Epoch 4

[ 0.07674028 -0.21314461  0.14657809 -0.94966029  0.7265409 ] 
errors =  7
Epoch 5

[ 0.07077806 -0.31468461  0.04861564 -0.94942633  0.72677687] 
errors =  3
Epoch 6

[ 0.10634375 -0.23809138  0.16590574 -1.0016462   0.80897133] 
errors =  12
Epoch 7

[ 0.11822039 -0.24443213  0.07951917 -1.10111029  0.77299692] 
errors =  5
Epoch 8

[ 0.10776175 -0.25871756  0.16291208 -1.06925642  0.7929193 ] 
errors =  1
Epoch 9

[ 0.13098428 -0.26811984  0.18152499 -1.11281104  0.83445889] 
errors =  8
Epoch 10

[ 0.08954705 -0.28991838  0.1510188  -1.17425096  0.78915271] 
errors =  4
Epoch 11

[ 0.10016474 -0.35937881  0.18060153 -1.17022045  0.83323132]

In [7]:
f = open('data5D_test.csv','r')
lines = f.readlines()
tests=[]
for l in lines:
    item=l.split()
    tests.append(np.array(item, dtype="float"))
print("values = ", tests)
f.close()

values =  [array([-0.21072208, -0.79501808,  0.28437907,  0.86837059,  0.73060236]), array([-0.12111626,  0.60824274, -0.47358205,  0.69620996,  0.21952921]), array([-0.23219499, -0.62105231,  0.05503385,  0.48291495,  0.8759104 ]), array([-0.59664385,  0.82638592,  0.35032913,  0.84496857,  0.66859734]), array([ 0.46476267,  0.8978245 ,  0.75454346,  0.20200565, -0.1353804 ]), array([-0.78494979, -0.60999804,  0.29379305, -0.8845752 , -0.71955901]), array([-0.29776664, -0.38832218,  0.88802089, -0.77137815,  0.64237691]), array([-0.64676409, -0.6279182 , -0.3026547 ,  0.31399474,  0.36810387]), array([ 0.73956971, -0.34440171,  0.88305262,  0.24552222, -0.60348933]), array([-0.44282619,  0.75906882,  0.90602738,  0.04138422, -0.59254111]), array([ 0.593805  , -0.41387575,  0.14167655,  0.06919212, -0.43647877]), array([ 0.23357398,  0.75990753, -0.66117702, -0.08285438, -0.09631611]), array([ 0.22716695,  0.53400283, -0.9568675 , -0.40931456,  0.48318165]), array([-0.40282615,  0.2986

In [8]:
guess=p2.predict(tests)

for i, item in enumerate(guess):
    print("The prediction for sample "+str(i)+" is "+str(item))
    
result=np.column_stack([tests, guess])


The prediction for sample 0 is -1
The prediction for sample 1 is -1
The prediction for sample 2 is 1
The prediction for sample 3 is -1
The prediction for sample 4 is -1
The prediction for sample 5 is 1
The prediction for sample 6 is 1
The prediction for sample 7 is -1
The prediction for sample 8 is -1
The prediction for sample 9 is -1
The prediction for sample 10 is -1
The prediction for sample 11 is -1
The prediction for sample 12 is 1
The prediction for sample 13 is -1
The prediction for sample 14 is -1
The prediction for sample 15 is -1
The prediction for sample 16 is -1
The prediction for sample 17 is 1
The prediction for sample 18 is 1
The prediction for sample 19 is 1
The prediction for sample 20 is -1
The prediction for sample 21 is 1
The prediction for sample 22 is 1
The prediction for sample 23 is 1
The prediction for sample 24 is -1
The prediction for sample 25 is 1
The prediction for sample 26 is 1
The prediction for sample 27 is 1
The prediction for sample 28 is -1
The pred

In [11]:
result


array([[-0.21072208, -0.79501808,  0.28437907,  0.86837059,  0.73060236,
        -1.        ],
       [-0.12111626,  0.60824274, -0.47358205,  0.69620996,  0.21952921,
        -1.        ],
       [-0.23219499, -0.62105231,  0.05503385,  0.48291495,  0.8759104 ,
         1.        ],
       ...,
       [-0.28960944, -0.15619135,  0.90507601,  0.59775244, -0.09617161,
        -1.        ],
       [ 0.67907071,  0.00613763,  0.47191729,  0.65510653,  0.4179075 ,
        -1.        ],
       [ 0.03854587,  0.86104938,  0.23411752, -0.25446469, -0.72048086,
        -1.        ]])

In [17]:
f = open('result.txt','w')
for x in result:
    print(x, file=f)
f.close()